In [1]:
import numpy as np

配列データの参照

In [13]:
a = np.arange(10); print('a= ', a)
a[-3]=100; print('a= ', a)

b=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]]); print('b= ', b)

b[0,-1], b[2,-2] = b[2,-2], b[0,-1]; print('b= ', b)

a=  [0 1 2 3 4 5 6 7 8 9]
a=  [  0   1   2   3   4   5   6 100   8   9]
b=  [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
b=  [[ 1  2  3 11]
 [ 5  6  7  8]
 [ 9 10  4 12]]


# スライス

In [18]:
a=np.arange(20)
b=-np.arange(10)
print(a)

a[0:20:2]=b
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 0  1 -1  3 -2  5 -3  7 -4  9 -5 11 -6 13 -7 15 -8 17 -9 19]


In [35]:
#他のスライス例

#スライス表記を代入演算可能だが、型が異なると、ブロードキャストが行われる。

a=np.arange(10); print('a= ', a)
b=-np.arange(12).reshape(3,4); print('b= ', b)


print('aを反対並びにする')
a_rev=a[::-1]   #反対並び
print('a_rev= ', a_rev)

print('b_2: 特定の行をスライス')
b_2 = b[2,:]; print('b_2= ', b_2);print(b_2.shape)
print('b3: 特定の列をスライス ※一行になってしまう')
b3 = b[:,3]; print('b3= ', b3);print(b3.shape)

a=  [0 1 2 3 4 5 6 7 8 9]
b=  [[  0  -1  -2  -3]
 [ -4  -5  -6  -7]
 [ -8  -9 -10 -11]]
aを反対並びにする
a_rev=  [9 8 7 6 5 4 3 2 1 0]
b_2: 特定の行をスライス
b_2=  [ -8  -9 -10 -11]
(4,)
b3: 特定の列をスライス ※一行になってしまう
b3=  [ -3  -7 -11]
(3,)


# reshape

In [44]:
a = np.arange(15); print('a= ', a)
a.shape=(3,5); print('a= ', a)

b=a.reshape(5,3); print('b= ', b)
b=np.reshape(a,(5,3)); print('b= ', b)

b=a.reshape((5,3)); print('b= ', b)
# b=a.reshape((6,-1)); print('b= ', b) #数が合わないと、エラーになる
c1=a.reshape(-1); print('c1= ', c1)
c2=a.reshape((-1,)); print('c2= ', c2)
c3=a.reshape((1,-1)); print('c3= ', c3)


a=  [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
a=  [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
b=  [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]
b=  [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]
b=  [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]
c1=  [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
c2=  [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
c3=  [[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]]


reshapeで型の変形

In [46]:
a = np.arange(12).reshape(3,4); print('a= ', a)

b=a.reshape(-1,6); print('b= ', b)

b=a.reshape(-1); print('b= ', b)

a=  [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
b=  [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
b=  [ 0  1  2  3  4  5  6  7  8  9 10 11]


# newaxis

In [55]:
a = np.arange(5); print('a= ', a);print('a.shape= ', a.shape)

a=a[np.newaxis,:]; 
print('a= ', a);print('a.shape= ', a.shape)

a = np.arange(5); print('a= ', a);print('a.shape= ', a.shape)
a=a[:,np.newaxis]; 
print('a= ', a);print('a.shape= ', a.shape)

a = np.arange(5); print('a= ', a);print('a.shape= ', a.shape)
a=a[np.newaxis,:, np.newaxis]; 
print('a= ', a);print('a.shape= ', a.shape)


a=  [0 1 2 3 4]
a.shape=  (5,)
a=  [[0 1 2 3 4]]
a.shape=  (1, 5)
a=  [0 1 2 3 4]
a.shape=  (5,)
a=  [[0]
 [1]
 [2]
 [3]
 [4]]
a.shape=  (5, 1)
a=  [0 1 2 3 4]
a.shape=  (5,)
a=  [[[0]
  [1]
  [2]
  [3]
  [4]]]
a.shape=  (1, 5, 1)


# ravel

配列を一次元にする、reshape(-1)相当

In [58]:
a = np.arange(12).reshape(3,4); print('a= ', a)

print('a.ravel= ', a.ravel())

a = np.arange(12).reshape(3,4); print('a= ', a)
print('a.reshape= ', a.reshape(-1))

a=  [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
a.ravel=  [ 0  1  2  3  4  5  6  7  8  9 10 11]
a=  [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
a.reshape=  [ 0  1  2  3  4  5  6  7  8  9 10 11]


# index array

In [66]:
#index番号で値を読み取る
#Indexがマイナスの場合、後ろから読み取る

a=np.arange(15)
print(a[np.array([5,7,7,-5,0])]) #([ * * * ]) index
print(a[np.array([[6,3],[-1,-2]])])


[ 5  7  7 10  0]
[[ 6  3]
 [14 13]]


In [70]:
a = np.arange(20).reshape(4,5); print('a= ', a)

x=np.array([0,2,-3]); print('x: ', x) 
y=np.array([2,1,4]); print('y: ', y)
print('a[x,y]= ', a[x,y]); #a[0,2], a[2,1], a[-3,4]を返す

a=  [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
x:  [ 0  2 -3]
y:  [2 1 4]
a[x,y]=  [ 2 11  9]


Bool 配列

In [83]:
#特定の条件に満たすセルを取り出すのに使える

a=np.linspace(-5,5,11); print('a= ', a)
a2=np.arange(-5,6); print('a2= ', a2)

b=np.array(x>0 for x in a);print('b= ', b)
c=np.array([x>0 for x in a]);print('c= ', c)

# print(a[b]) 　　エラー：　IndexError: arrays used as indices must be of integer (or boolean) type
print(a[c])

a=  [-5. -4. -3. -2. -1.  0.  1.  2.  3.  4.  5.]
a2=  [-5 -4 -3 -2 -1  0  1  2  3  4  5]
b=  <generator object <genexpr> at 0x7f09508a74d0>
c=  [False False False False False False  True  True  True  True  True]
[1. 2. 3. 4. 5.]


In [93]:
a=np.linspace(0,15,16).reshape(4,4); print('a= ', a)

b=np.array([True, True, True, False]);print('a[b]= ', a[b])

b=np.array([True, True, True, False]);print('a[:,b]= ', a[:,b])

a=  [[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]
 [12. 13. 14. 15.]]
a[b]=  [[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
a[:,b]=  [[ 0.  1.  2.]
 [ 4.  5.  6.]
 [ 8.  9. 10.]
 [12. 13. 14.]]
