In [3]:
# -*- coding: utf-8 -*-
import numpy as np

# 配列種類
array       リストやタプルを配列に変換
zeros       ０配列；引数として配列の型をタプルで渡す
zeros_like  ０配列；引数の配列と同じ型の配列を返す
ones
onee_like
full
full_like
empty       値を初期化せず指定の型の配列を返す
arange      等間隔の数からなる１次元配列を生成
linspace    等間隔の数からなる１次元配列を生成
logspace    成分の対数が等間隔になる１次元配列
meshgrid    碁盤の目状の２次元座標を軸ごとに分けて返す
identity    単位行列に対応する配列を返す、引数は行列の次数
eye         単位行列に対応する配列を返す；引数は行列の行数ｍと列数ｎ
diag        １次元のリストやタプルや配列からそれらが対角に並ぶ２次元配列を返す
tri         対角とそれ以下の部分が全て１で、他が０である行列を返す
vander      Vandermonde行列を返す

In [2]:
z1 = np.zeros(3,);                  print('z1 = ', z1)
z2 = np.zeros((2,3));               print('z2 = ', z2)
L = [[1.0,2,3],[4,5,6],[7,8,9]]
z3 = np.zeros_like(L, dtype = int); print('z3 = ',z3)

z1 =  [0. 0. 0.]
z2 =  [[0. 0. 0.]
 [0. 0. 0.]]
z3 =  [[0 0 0]
 [0 0 0]
 [0 0 0]]


In [3]:
a = np.empty((3,3));                print('a= ',a)
b = np.empty((3,3), dtype=int);     print('b= ',b)

a=  [[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
b=  [[4607182418800017408 4611686018427387904 4613937818241073152]
 [4616189618054758400 4617315517961601024 4618441417868443648]
 [4619567317775286272 4620693217682128896 4621256167635550208]]


In [4]:
# only work in ipython; ones cost more time

N=10000
%timeit np.zeros((N,N))     
%timeit np.ones((N,N))     #cost more than 10000 times 
%timeit np.empty((N,N))

11.9 µs ± 540 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
376 ms ± 134 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
12.8 µs ± 718 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


### array(range(n))とarange(n)の比較

-arangeはlinspaceと同じ、等間隔配列を生成する関数

-そのため、引数が正整数一つのとき、array(range(n))と同じ結果を得る 

-arange(n)が約80倍速い

In [5]:
print(np.array(range(10)))
print(np.arange(10))

n = 1000000
%timeit a = np.array(range(n))
%timeit b = np.arange(n)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
216 ms ± 24.4 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
2.65 ms ± 120 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


### comparison of arange and linspace 

In [6]:
p = np.pi

#arange(start, stop, step, dtype)
#linspace(start, stop, num)

a = np.arange(-p,p,p/6) 
b = np.linspace(-p,p,13)
#print(a)
#print(b)

print(type(a[0]))
print(type(b[0]))  #同じF64なのに、なぜか表示が違う

#print(np.arange(-p,p,p/6))    
#print(np.linspace(-p,p,13))

<class 'numpy.float64'>
<class 'numpy.float64'>


### Logspace(start, stop, num=50, endpoint=True, base=10.0, dtype=None)
※引数：6つ
※返り値：baseのstart乗からbaseのend乗までの数値を、baseを底とする対数をとると、num個に均等に配置された数の配列を返す
※Endpoint：最後の値であるbaseのstop乗を場外するかどうか

※arangeやlinspaceは等差数列
※logspaceは等比数列を生成

※例：

In [7]:
a = np.logspace(0,10,11,base=0.5)
print('a = ', a)
print('log2(a) = ', np.log2(a))

a =  [1.000000e+00 5.000000e-01 2.500000e-01 1.250000e-01 6.250000e-02
 3.125000e-02 1.562500e-02 7.812500e-03 3.906250e-03 1.953125e-03
 9.765625e-04]
log2(a) =  [  0.  -1.  -2.  -3.  -4.  -5.  -6.  -7.  -8.  -9. -10.]


In [5]:
#Meshgrid

x=np.linspace(1,3,3)
y=np.linspace(-1,3,5)

X,Y = np.meshgrid(x,y) ; print ('X= ', X); print ('Y= ', Y)

X=  [[1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]]
Y=  [[-1. -1. -1.]
 [ 0.  0.  0.]
 [ 1.  1.  1.]
 [ 2.  2.  2.]
 [ 3.  3.  3.]]


In [8]:
# Identity & Eye

print(np.identity(5))
print(np.eye(4,6,2))
print(np.eye(4,6,0))
print(np.eye(6,3,-1))

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[[0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]
[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]]
[[0. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [14]:
#diag(一次元のリストやタプル) 
#tri（m,n）:対角上０対角下１

a = np.arange(1,13).reshape((4,3)); print('a= ', a)
b = np.diag([1,2,3,4]); print('b= ', b)
c = np.diag(a); print('c= ', c)
d = np.tri(3); print('d= ', d)
e = np.tri(4,5); print('e= ', e)

a=  [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
b=  [[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]
c=  [1 5 9]
d=  [[1. 0. 0.]
 [1. 1. 0.]
 [1. 1. 1.]]
e=  [[1. 0. 0. 0. 0.]
 [1. 1. 0. 0. 0.]
 [1. 1. 1. 0. 0.]
 [1. 1. 1. 1. 0.]]


In [17]:
#Vandermonde
#np.vander(x, N=None, increasing=False)

x = np.array([1,2,3,5])
v1 = np.vander(x); print('v1 = \n', v1)
v2 = np.vander(x, increasing=True); print('v2 = \n', v2)
v3 = np.vander(x, 2, increasing=True); print('v3 = \n', v3)
v4 = np.vander(x, 3, increasing=True); print('v4 = \n', v4)

v1 = 
 [[  1   1   1   1]
 [  8   4   2   1]
 [ 27   9   3   1]
 [125  25   5   1]]
v2 = 
 [[  1   1   1   1]
 [  1   2   4   8]
 [  1   3   9  27]
 [  1   5  25 125]]
v3 = 
 [[1 1]
 [1 2]
 [1 3]
 [1 5]]
v4 = 
 [[ 1  1  1]
 [ 1  2  4]
 [ 1  3  9]
 [ 1  5 25]]
