# Kronecker積(product)
kron(A,B)  = A(m,n)とB(p,q)の外積　= [a(m,n)B]


In [18]:
import numpy as np

A = np.arange(1,10).reshape(3,3)
B = np.arange(1,10).reshape(3,3)
print('A= ')
print(A)
print('B= ')
print(B)
C = np.kron(A,B)
print('kron(A,B)= ')
print(C)

D = A*B
print('D = A*B =')
print(D)

E = np.dot(A,B)
print('E = A.*B =')
print(E)

A= 
[[1 2 3]
 [4 5 6]
 [7 8 9]]
B= 
[[1 2 3]
 [4 5 6]
 [7 8 9]]
kron(A,B)= 
[[ 1  2  3  2  4  6  3  6  9]
 [ 4  5  6  8 10 12 12 15 18]
 [ 7  8  9 14 16 18 21 24 27]
 [ 4  8 12  5 10 15  6 12 18]
 [16 20 24 20 25 30 24 30 36]
 [28 32 36 35 40 45 42 48 54]
 [ 7 14 21  8 16 24  9 18 27]
 [28 35 42 32 40 48 36 45 54]
 [49 56 63 56 64 72 63 72 81]]
D = A*B =
[[ 1  4  9]
 [16 25 36]
 [49 64 81]]
E = A.*B =
[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]


In [12]:
A = np.arange(1,7).reshape(2,3)
B = np.arange(1,5).reshape(2,2)
print('A= ')
print(A)
print('B= ')
print(B)
C = np.kron(A,B)
print('kron(A,B)= ')
print(C)


A= 
[[1 2 3]
 [4 5 6]]
B= 
[[1 2]
 [3 4]]
kron(A,B)= 
[[ 1  2  2  4  3  6]
 [ 3  4  6  8  9 12]
 [ 4  8  5 10  6 12]
 [12 16 15 20 18 24]]


ValueError: operands could not be broadcast together with shapes (2,3) (2,2) 

## 三角行列

1. tril(a) 対角線以下の三角配列
2. triu(a) 対角線以上の三角配列

In [24]:
a = np.arange(1,13).reshape(3,4)

print('tri_low = ')
print(np.tril(a))
print('tri_upper = ')
print(np.triu(a))

tri_low = 
[[ 1  0  0  0]
 [ 5  6  0  0]
 [ 9 10 11  0]]
tri_upper = 
[[ 1  2  3  4]
 [ 0  6  7  8]
 [ 0  0 11 12]]


## オープンメッシュ Open mesh


1. np.ix_(Rows, Columns) でタプルを返す
2. タプルのを配列に入れることで、行列を抽出する。

下記の例では、指定のリストで列と行を抽出する


In [38]:
A = np.array([[i+k*1j for k in range(5)] for i in range(6)])
print('A = \n', A)

R = [1,3]
C = [0,2,4]
print('A[R,C] = \n', A[np.ix_(R,C)])

import pprint
pprint.pprint(np.ix_(R,C), width=40)
print(type(np.ix_(R,C)))

A = 
 [[0.+0.j 0.+1.j 0.+2.j 0.+3.j 0.+4.j]
 [1.+0.j 1.+1.j 1.+2.j 1.+3.j 1.+4.j]
 [2.+0.j 2.+1.j 2.+2.j 2.+3.j 2.+4.j]
 [3.+0.j 3.+1.j 3.+2.j 3.+3.j 3.+4.j]
 [4.+0.j 4.+1.j 4.+2.j 4.+3.j 4.+4.j]
 [5.+0.j 5.+1.j 5.+2.j 5.+3.j 5.+4.j]]
A[R,C] = 
 [[1.+0.j 1.+2.j 1.+4.j]
 [3.+0.j 3.+2.j 3.+4.j]]
(array([[1],
       [3]]),
 array([[0, 2, 4]]))
<class 'tuple'>
