# ブロードキャストとデータ型

In [1]:
# -*- coding: utf-8 -*-
import numpy as np

In [ ]:
同じ型の場合

In [4]:
a = np.arange(12).reshape(3,4); print('a= ', a)
b = np.arange(12).reshape(3,4); 
print('a*b ', a*b)

a=  [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
a*b  [[  0   1   4   9]
 [ 16  25  36  49]
 [ 64  81 100 121]]


同じ型の場合: 配列とスカラーの演算（べき乗）

In [6]:
a = np.arange(12).reshape(3,4); print('a= ', a)
b = a**2; 
print('b= ', b)

a=  [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
b=  [[  0   1   4   9]
 [ 16  25  36  49]
 [ 64  81 100 121]]


異なる型の場合 : 次元を合わせる

In [12]:
a = np.arange(5); print('a= ', a)
b = np.arange(24).reshape(4,3,2); #print('b= ', b)

print("a.ndim= ", a.ndim)
print("b.ndim= ", b.ndim)

while a.ndim > b.ndim:
    b=b[np.newaxis, :]
while b.ndim > a.ndim:
    a=a[np.newaxis, :]

print('a.shape= ', a.shape)
print('b.shape= ', b.shape)

a=  [0 1 2 3 4]
a.ndim=  1
b.ndim=  3
a.shape=  (1, 1, 5)
b.shape=  (4, 3, 2)


#### ブロードキャスト可能かどうか？
1. 次元の小さい配列の先頭にnewaxisを追加し、同じ次元にする
2. ブロードキャスト可能の条件（or）：
(1) 各次元のShapeは同じである
(2) 各次元、どちらかが１
    
　　3-1-4　　　3-1-4
　　1-3-1      1-1-3
　　○○○     ○○☓

In [18]:
a = np.arange(12).reshape(3,1,4); print('a= ', a)
b = np.array([0,100,1000]).reshape(1,3,1); print('b= ', b)
print('a+b= ', a+b)

#314 vs 113 case of error
#c = np.array([0,100,1000]).reshape(1,1,3); print('c= ', c) 
#print('a+c= ', a+c)

a=  [[[ 0  1  2  3]]

 [[ 4  5  6  7]]

 [[ 8  9 10 11]]]
b=  [[[   0]
  [ 100]
  [1000]]]
a+b=  [[[   0    1    2    3]
  [ 100  101  102  103]
  [1000 1001 1002 1003]]

 [[   4    5    6    7]
  [ 104  105  106  107]
  [1004 1005 1006 1007]]

 [[   8    9   10   11]
  [ 108  109  110  111]
  [1008 1009 1010 1011]]]


注意！！ブロードキャスト例

In [29]:
a=np.arange(1,10)
b=np.reshape(a,(9,1))
print(a*b)

print(a.shape)
print(b.shape)

c=np.arange(1,5) #.reshape(2,2)
d=np.reshape(c,(1,4))
print(c*d)
print(c.shape)
print(d.shape)

[[ 1  2  3  4  5  6  7  8  9]
 [ 2  4  6  8 10 12 14 16 18]
 [ 3  6  9 12 15 18 21 24 27]
 [ 4  8 12 16 20 24 28 32 36]
 [ 5 10 15 20 25 30 35 40 45]
 [ 6 12 18 24 30 36 42 48 54]
 [ 7 14 21 28 35 42 49 56 63]
 [ 8 16 24 32 40 48 56 64 72]
 [ 9 18 27 36 45 54 63 72 81]]
(9,)
(9, 1)
[[ 1  4  9 16]]
(4,)
(1, 4)


ブロードキャスト代入不可能の例

In [38]:
a = np.arange(12).reshape(3,4); print('a= ', a)
b = np.arange(4).reshape(4,1); print('b= ', b)
c = -np.arange(4); print('c= ', c)
print(a.shape)
print(b.shape)
print(c.shape)

#演算OK　代入OK
print('a*c=', a*c) #ブロードキャスト積　　(3,4) * (4,) 
a[:,:]=c #ブロードキャスト演算
print('a= ', a)

#演算OK　代入NG
print('b*c=', b*c) #ブロードキャスト積　　(3,4) * (4,) 
b[:,:]=c #ブロードキャスト演算 
         # ValueError: could not broadcast input array from shape (4) into shape (4,1)
print('b= ', b)

a=  [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
b=  [[0]
 [1]
 [2]
 [3]]
c=  [ 0 -1 -2 -3]
(3, 4)
(4, 1)
(4,)
a*c= [[  0  -1  -4  -9]
 [  0  -5 -12 -21]
 [  0  -9 -20 -33]]
a=  [[ 0 -1 -2 -3]
 [ 0 -1 -2 -3]
 [ 0 -1 -2 -3]]
b*c= [[ 0  0  0  0]
 [ 0 -1 -2 -3]
 [ 0 -2 -4 -6]
 [ 0 -3 -6 -9]]


ValueError: could not broadcast input array from shape (4) into shape (4,1)

#### ブロードキャストとIndex配列を組み合わせし、部分行列を自在に切り出す

行を切り取る：
[[m][n]]
Shape [x,1]

列を切り取る：
[m,n] 
Shape　[x,]

Shape　[x,]→ [x,1]　にするのに、ブロードキャストの出番；R[:,newaxis] :がx, newaxisでないところに１になる

In [55]:
print('1. 実部０〜５　虚部０〜４の配列を作る')
A = np.array([[i+k*1j for k in range(5)] for i in range(6)])  #最初は列を増やされ、次に行増やされた
print('A = ', A)
print('　')
print('2. 切り取り指示用の配列を作る')
R = np.array([1,3])
C = np.array([0,2,4])
print('R = ', R)
print('C = ', C)
print('　')
print('3. 切り取り指示用の配列を作る')
print('R.shape= ', R.shape)
print('R[:,np.newaxis].shape= ', R[:,np.newaxis].shape)
print('A[R,C] = ', A[R[:,np.newaxis], C])


# print('A[R,C] = ', A[R, C])
# IndexError: shape mismatch: indexing arrays could not be broadcast together with shapes (2,) (3,) 


1. 実部０〜５　虚部０〜４の配列を作る
A =  [[0.+0.j 0.+1.j 0.+2.j 0.+3.j 0.+4.j]
 [1.+0.j 1.+1.j 1.+2.j 1.+3.j 1.+4.j]
 [2.+0.j 2.+1.j 2.+2.j 2.+3.j 2.+4.j]
 [3.+0.j 3.+1.j 3.+2.j 3.+3.j 3.+4.j]
 [4.+0.j 4.+1.j 4.+2.j 4.+3.j 4.+4.j]
 [5.+0.j 5.+1.j 5.+2.j 5.+3.j 5.+4.j]]
　
2. 切り取り指示用の配列を作る
R =  [1 3]
C =  [0 2 4]
　
3. 切り取り指示用の配列を作る
R.shape=  (2,)
R[:,np.newaxis].shape=  (2, 1)
A[R,C] =  [[1.+0.j 1.+2.j 1.+4.j]
 [3.+0.j 3.+2.j 3.+4.j]]
