In [6]:
# -*- coding: utf-8 -*-
import numpy as np

# random.seed()

1. random.seed(n)：乱数生成の種
2. random.uniform(l,h)：一様乱数
3. random.randint(l,h,size=(m,n))：整数の一様乱数
4. random.randn(m,n)：平均０分散１の正規分布に従う乱数
5. random.standard_normal：標準正規分布に従う乱数（引数はタプル可）
6. random.beta：ベータ分布に従う乱数
7. random.binomial：２項分布に従う乱数
8. random.poisson：Poisson分布に従う乱数
9. random.permutation(range(10)))：ランダムな順列
10. random.multivariate_normal：多次元正規分布
11. random.choice：一次元配列からのランダムサンプリング

In [23]:
import numpy.random as random
random.seed(100)
print(random.uniform(5,5.01)) #一様乱数、Seedと範囲決まれば、出力ずーと同じ

print(random.randint(-10,0,size=(2,3)))
print(random.randn(3,3))
print(random.permutation(range(10)))
a=np.arange(-10,11)
print(random.choice(a,size=6,replace=False,p=None))
print(random.choice(a,size=(2,4),replace=True,p=None)) #replace:重複許可


5.00543404941791
[[ -7  -3  -3]
 [-10  -6  -8]]
[[-0.53934796 -0.5833315   1.073201  ]
 [-0.13702713  0.17086301 -0.59970748]
 [ 2.65975058  0.99683627 -0.23198063]]
[9 5 2 0 8 6 1 7 3 4]
[-7 -6  2  7  0 -9]
[[  7  -6   8  -2]
 [  9   4 -10   3]]
