# 配列の中身を判定する関数

* all　　成分が全てTrueならTrueを返す
* any　　成分のどれがTrueならTrueを返す
* array_equal　配列が等しければTrueを返す
* allclose　　配列の成分が全て近い数値かどうかを判断する
* unique　　　重複する成分の除去
* nonzero　　 非ゼロ成分を取り出す

#### all, any, array_equal, allclose

In [9]:
import numpy as np

a = np.linspace(0,18,10); print('a= ',a)
print(np.all(a%2==0)) #True
print(np.any(a<0)) #False
print(np.any(a<=0)) #True

a=  [ 0.  2.  4.  6.  8. 10. 12. 14. 16. 18.]
True
False
True


In [13]:
A = np.tri(3,3); print('A= \n',A)
B = np.linalg.inv(A); print('B= \n',B) #BにAの逆行列を計算する
C = np.dot(A,B); print('C= \n',C)
print(np.array_equal(C, np.identity(3))) #True
print(np.allclose(C, np.identity(3))) #True

A= 
 [[1. 0. 0.]
 [1. 1. 0.]
 [1. 1. 1.]]
B= 
 [[ 1.  0.  0.]
 [-1.  1.  0.]
 [ 0. -1.  1.]]
C= 
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
True
True


#### allclose(a,b,rtol=1.e-5,atol=1.e-8)

|a'-b'| <= (atol + rtol * b')
* atol: 絶対誤差
* rtol: 相対誤差

In [23]:
print(np.allclose(C, np.identity(3)-0.01,rtol=1.e-5,atol=1.e-8)) #False
print(np.allclose(C, np.identity(3)-1.e-7,rtol=1.e-5,atol=1.e-8)) #False
print(np.allclose(C, np.identity(3)-1.e-8,rtol=1.e-5,atol=1.e-8)) #True

False
False
True
