# 配列操作関数リスト

* Sort     ソート
* argsort  インデックスソート  
* ravel    配列をフラット（一次元）にする
* flatten  配列をフラット（一次元）にしたコピーを返す
* delete   削除
* insert   挿入
* append   追加
* tile     パターンを繰り返す
* vstack   二次元配列（行列）を垂直方向（0軸）に沿って貼り合わせる
* hastack  二次元配列（行列）を水平方向（1軸）に沿って貼り合わせる
* copy     配列をコピー
* alen     0軸方向の長さを返す





In [17]:
import numpy as np

a = -np.arange(12).reshape(3,4); print('a = \n', a)

sa = np.sort(a); print('sa = \n', sa)
sa1 = np.sort(a, axis = 0); print('sa_axis0 = \n', sa1)
sa2 = np.sort(a, axis = 1); print('sa_axis1 = \n', sa2)

a = 
 [[  0  -1  -2  -3]
 [ -4  -5  -6  -7]
 [ -8  -9 -10 -11]]
sa = 
 [[ -3  -2  -1   0]
 [ -7  -6  -5  -4]
 [-11 -10  -9  -8]]
sa_axis0 = 
 [[ -8  -9 -10 -11]
 [ -4  -5  -6  -7]
 [  0  -1  -2  -3]]
sa_axis1 = 
 [[ -3  -2  -1   0]
 [ -7  -6  -5  -4]
 [-11 -10  -9  -8]]


In [18]:
a = -np.arange(12).reshape(3,4); print('a = \n', a)

a[1,1], a[1,2] = a[1,2], a[1,1]  # 行列それぞれ独立してソートしているよう
b = a; print('b = \n', b)

sb = np.sort(b); print('sb = \n', sb)
sb1 = np.sort(b, axis = 0); print('sb_axis0 = \n', sb1)
sb2 = np.sort(b, axis = 1); print('sb_axis1 = \n', sb2)

a = 
 [[  0  -1  -2  -3]
 [ -4  -5  -6  -7]
 [ -8  -9 -10 -11]]
b = 
 [[  0  -1  -2  -3]
 [ -4  -6  -5  -7]
 [ -8  -9 -10 -11]]
sb = 
 [[ -3  -2  -1   0]
 [ -7  -6  -5  -4]
 [-11 -10  -9  -8]]
sb_axis0 = 
 [[ -8  -9 -10 -11]
 [ -4  -6  -5  -7]
 [  0  -1  -2  -3]]
sb_axis1 = 
 [[ -3  -2  -1   0]
 [ -7  -6  -5  -4]
 [-11 -10  -9  -8]]


argsort: 配列aをソートしたときのインデックス配列を返す。

In [26]:
import numpy.random as random
a = random.randn(10)
c = random.randn(3,4)
b = np.argsort(a)
print('a = \n', a)
print('b = \n', b)
print('a[b] = \n', a[b])

print('c= \n', c)
print('np.argsort(c) = \n', np.argsort(c))
d= np.argsort(c)
# print('c[d] = \n', c[d]) 二次元配列は簡単にIndexでソートできない

a = 
 [-0.00569679  1.4803106   0.27674516  0.24454502  0.66651908  0.71734438
  0.63023192  0.02595962 -1.72611863  0.49422948]
b = 
 [8 0 7 3 2 9 6 4 5 1]
a[b] = 
 [-1.72611863 -0.00569679  0.02595962  0.24454502  0.27674516  0.49422948
  0.63023192  0.66651908  0.71734438  1.4803106 ]
c= 
 [[-0.08233887  0.32828826 -1.47874716 -1.93568677]
 [ 0.99878306  0.75178979 -0.54869733 -1.07728085]
 [ 1.58087053 -1.32851181 -0.02052937  0.58472426]]
np.argsort(c) = 
 [[3 2 0 1]
 [3 2 1 0]
 [1 2 3 0]]


#### ravel & flatten & reshape(-1)

* flatten      遅い。フラットな配列のコピーを返すから時間かかる
* ravel　　　　速い。見方(view)を変えているだけで、もとの配列を書き換えると影響されてしまう
* reshape(-1)　やや速い。見方(view)を変えているだけで、もとの配列を書き換えると影響されてしまう

In [31]:
a = np.arange(12).reshape(3,4); print('a = \n', a)

b1 = a.flatten()
b2 = a.ravel()
b3 = a.reshape(-1)

a[0,0] = 100

print('b1_flattern = \n', b1)
print('b2_ravel = \n', b2)
print('b3_reshape = \n', b3)

a = 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
b1_flattern = 
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
b2_ravel = 
 [100   1   2   3   4   5   6   7   8   9  10  11]
b3_reshape = 
 [100   1   2   3   4   5   6   7   8   9  10  11]


In [33]:
#実行時間の確認

a = random.randn(3000,3000)
%timeit -n 100 b1 = a.flatten()  #34.8 ms ± 2.16 ms
%timeit -n 100 b2 = a.ravel()    #277 ns ± 19.9 ns
%timeit -n 100 b3 = a.reshape(-1)  #801 ns ± 25.7 ns

36.5 ms ± 2.3 ms per loop (mean ± std. dev. of 7 runs, 100 loops each)
483 ns ± 27.6 ns per loop (mean ± std. dev. of 7 runs, 100 loops each)
1.59 µs ± 23.6 ns per loop (mean ± std. dev. of 7 runs, 100 loops each)


#### delete: 
    
delete(arr, obj, axis)
* arr:   対象配列を指定
* obj:   削除する場所のインデックスかそれらのシーケンス；またはスライス表記が入り、
* axis:  軸を指定

In [46]:
#a = np.array([[i + k*1j for k in range(4)] for i in range(3)]); print('a= \n',a)
a = np.arange(1,37).reshape(6,6); print('a= \n',a)

print('特定な要素を削除')
print(np.delete(a,1)) # delete no.10 element　要素指定したら、配列が展開される
print('指定の行を削除')
print(np.delete(a,1,0)) #delete row no.1
print('指定の列を削除')
print(np.delete(a,1,1)) #delete column no.1
print('複雑条件の削除')
print(np.delete(a,np.s_[0::2],1)) #第0列目から2列ごとに取り除く
print('複雑条件の削除２')
print(np.delete(a,np.s_[0::2],0)) #第0行目から2行ごとに取り除く


print(np.s_[0::2])  
#slice(0, None, 2)

a= 
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]
特定な要素を削除
[ 1  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25
 26 27 28 29 30 31 32 33 34 35 36]
指定の行を削除
[[ 1  2  3  4  5  6]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]
指定の列を削除
[[ 1  3  4  5  6]
 [ 7  9 10 11 12]
 [13 15 16 17 18]
 [19 21 22 23 24]
 [25 27 28 29 30]
 [31 33 34 35 36]]
複雑条件の削除
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]
 [20 22 24]
 [26 28 30]
 [32 34 36]]
複雑条件の削除２
[[ 7  8  9 10 11 12]
 [19 20 21 22 23 24]
 [31 32 33 34 35 36]]
slice(0, None, 2)


#### insert: 配列に新たに値を挿入する関数である

insert(arr, obj, values, axis)

* 軸指定しなかった場合、配列はフラットFlatになる
* 挿入はして場所の**前**に挿入される

In [56]:
a = a = np.arange(1,13).reshape(3,4); print('a= \n',a)
print('5番目の要素(0start)の前に100を挿入する')
print(np.insert(a,5,100))
print('3列目の要素をコピーして、列0の前に挿入する')
print(np.insert(a,0,a[:,3],axis=1))
print('3列目の要素をコピーして、列1の前に挿入する')
print(np.insert(a,1,a[:,3],axis=1))

a= 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
5番目の要素(0start)の前に100を挿入する
[  1   2   3   4   5 100   6   7   8   9  10  11  12]
3列目の要素をコピーして、列0の前に挿入する
[[ 4  1  2  3  4]
 [ 8  5  6  7  8]
 [12  9 10 11 12]]
3列目の要素をコピーして、列1の前に挿入する
[[ 1  4  2  3  4]
 [ 5  8  6  7  8]
 [ 9 12 10 11 12]]


#### append:　要素を配列の**最後**に加える関数
append(arr, values, axis)
* 軸を与えられなかった場合、arrとvalueはともにフラットにされる

#### tile, hstack, vstack
小さな2次元配列を繰り返し使い、より大きな配列を作るメソッド
* tile(a, reps)　配列aをrepsの型だけ繰り返す
* hstack(tup)　配列のタプルtup成分をそれぞれ水平方向に結合する
* vstack(tup)　配列のタプルtup成分をそれぞれ垂直方向に結合する

In [60]:
a = a = np.arange(4).reshape(2,2); print('a= \n',a)
print('2*2の行列を2*6に三回コピーする')
print('tiled a = \n', np.tile(a,3))
print('2*2の行列を(2,1)(4*2)の配置でコピーする')
print('tiled a = \n', np.tile(a,(2,1)))

a= 
 [[0 1]
 [2 3]]
2*2の行列を2*6に三回コピーする
tiled a = 
 [[0 1 0 1 0 1]
 [2 3 2 3 2 3]]
2*2の行列を(2,1)(4*2)の配置でコピーする
tiled a = 
 [[0 1]
 [2 3]
 [0 1]
 [2 3]]


In [66]:
b = np.identity(2); print('b= \n',b)
print('b.T= \n',b.T)
print('配列aとbを水平につなぐ')
print(np.hstack((a,b)))
print('配列aとbを垂直につなぐ')
print(np.vstack((a,b)))
#print(np.vstack((a.T,b.T)))

b= 
 [[1. 0.]
 [0. 1.]]
b.T= 
 [[1. 0.]
 [0. 1.]]
配列aとbを水平につなぐ
[[0. 1. 1. 0.]
 [2. 3. 0. 1.]]
配列aとbを垂直につなぐ
[[0. 1.]
 [2. 3.]
 [1. 0.]
 [0. 1.]]


#### copy & alen
copy(a, order) 
* order　メモリーレイアウトのオプション；既定値はKであり、できるだけオリジナルのaに従う意味

alen   引数として与えられた配列の0軸方向の長さを返す

In [69]:
a = np.arange(10)
b = a
c = np.copy(a)

a[0] = -100

print(a[0] == b[0]) #True
print(a[0] == c[0]) #False

a.shape = (2,5)
print(np.alen(a)) # 2 行数

True
False
2
