# NumPyの関数

1. Numpyのデータ構造：ndarray　多次元配列
2. ユニバーサル関数とそうでない関数
3. 一次元はベクトル、二次元は行列

数学定数とユニバーサル関数
1. Pi 
2. e
3. euler_gamma

In [3]:
import numpy as np

print('pi=', np.pi)
print('e=', np.e)
print('euler_gamma=', np.euler_gamma)

pi= 3.141592653589793
e= 2.718281828459045
euler_gamma= 0.5772156649015329


#### 基礎数学関数（ユニバーサル関数）

In [8]:
np.add(1,1)
np.subtract(2,1)
np.multiply(2,1)
np.divide(2,2)
"""
np.logaddexp
np.logaddexp2
np.true_devide
np.floor_devide
np.negative
np.power
np.remainder
np.mod
np.fmod
np.absolute
np.rint
np.sign
np.conj
np.exp
np.exp2
np.log
np.log2
np.log10
np.expm1
np.log1p
np.sqrt
np.square
np.reciprocal
"""

'\nnp.logaddexp\nnp.logaddexp2\nnp.true_devide\nnp.floor_devide\nnp.negative\nnp.power\nnp.remainder\nnp.mod\nnp.fmod\nnp.absolute\nnp.rint\nnp.sign\nnp.conj\nnp.exp\nnp.exp2\nnp.log\nnp.log2\nnp.log10\nnp.expm1\nnp.log1p\nnp.sqrt\nnp.square\nnp.reciprocal\n'

In [12]:
print(np.add(1,1))
print(np.subtract(2,1))
print(np.multiply(2,1))
print(np.divide(2,2))
"""
np.logaddexp(x1, x2)   #log(exp(x1) + exp(x2))
np.logaddexp2(x1, x2)  #log2(2**x1 + 2**x2).



2
1
2
1.0


'\nnp.logaddexp(x1, x2)   #log(exp(x1) + exp(x2))\nnp.logaddexp2(x1, x2)  #log2(2**x1 + 2**x2).\nnp.true_devide(x1, x2)  #Returns a true division of the inputs, element-wise.\nnp.floor_devide(x1, x2) \nnp.negative(x1, x2) \nnp.power(x1, x2) \nnp.remainder(x1, x2) \nnp.mod(x1, x2) \nnp.fmod(x1, x2) \nnp.absolute(x1, x2) \nnp.rint(x1, x2) \nnp.sign\nnp.conj\nnp.exp\nnp.exp2\nnp.log\nnp.log2\nnp.log10\nnp.expm1\nnp.log1p\nnp.sqrt\nnp.square\nnp.reciprocal\n'

In [19]:
x = np.arange(5)
print(np.true_divide(x, 4))
print(x/4)
print(np.floor_divide(x, 4))
print(x//4)

[0.   0.25 0.5  0.75 1.  ]
[0.   0.25 0.5  0.75 1.  ]
[0 0 0 0 1]
[0 0 0 0 1]


In [ ]:

np.negative(x1, x2) 
np.power(x1, x2) 
np.remainder(x1, x2) 
np.mod(x1, x2) 
np.fmod(x1, x2) 
np.absolute(x1, x2) 
np.rint(x1, x2) 
np.sign
np.conj
np.exp
np.exp2
np.log
np.log2
np.log10
np.expm1
np.log1p
np.sqrt
np.square
np.reciprocal
"""

In [27]:
print(np.negative([[-5,5],[4,4]]))

[[ 5 -5]
 [-4 -4]]


In [31]:
print(np.power(3,2)) #3**2
print(np.power(3,3)) #3**3

9
27


In [39]:
print('np.remainder')
print(np.remainder(10,2))
print(np.remainder(10,3))
print(np.remainder(10,4))
print(np.remainder(10,5))
print('np.mod')
print(np.mod(10,2))
print(np.mod(10,3))
print(np.mod(10,4))
print(np.mod(10,5))
print('np.fmod')
print(np.fmod(10,2))
print(np.fmod(10,3))
print(np.fmod(10,4))
print(np.fmod(10,5))

np.remainder
0
1
2
0
np.mod
0
1
2
0
np.fmod
0
1
2
0


In [15]:
np.remainder(x1, x2) 
np.mod(x1, x2) 
np.fmod(x1, x2) 
np.absolute(x1, x2) 
np.rint(x1, x2) 
np.sign
np.conj
np.exp
np.exp2
np.log
np.log2
np.log10
np.expm1
np.log1p
np.sqrt
np.square
np.reciprocal
"""

array([0.  , 0.25, 0.5 , 0.75, 1.  ])